"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from secrets import token_urlsafe
import socket
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
sys.path.append(os.path.join(BASE_DIR, 'apps'))


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 't', 'yes', 'y', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


def get_lan_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('10.255.255.255', 1))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return None


def database_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {'postgres', 'postgresql'} or not parsed.path.strip('/'):
        raise ValueError('DATABASE_URL must be a PostgreSQL connection URL.')

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
        'OPTIONS': {key: values[-1] for key, values in parse_qs(parsed.query).items()},
    }

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fails closed: a host that does not explicitly ask for debug gets production
# behaviour. Every local entrypoint (backend/.env, docker-compose.yml) already
# sets DJANGO_DEBUG explicitly, so this only changes what an *unconfigured*
# environment does -- and there it should never be the permissive one.
DEBUG = env_bool('DJANGO_DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = token_urlsafe(50)
    else:
        raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False.')

# Reaching the dev server from a phone on the same Wi-Fi is a development
# affordance: it costs a socket call at import time and means nothing on a PaaS
# box, where the only valid hostname is the one the platform assigns.
_LAN_IP = get_lan_ip() if DEBUG else None
_extra_hosts = [f'{_LAN_IP}', f'{_LAN_IP}:3000'] if _LAN_IP else []

# Render injects the service's public hostname into every container. Reading it
# here breaks the chicken-and-egg of the first deploy -- you cannot put the URL
# in ALLOWED_HOSTS before the service exists to have one.
RENDER_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,aixia') + _extra_hosts
if RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'documents',
    'chat'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000',
)
if _LAN_IP:
    CORS_ALLOWED_ORIGINS += [
        f'http://{_LAN_IP}:3000',
        f'http://{_LAN_IP}',
    ]

# Unlike ALLOWED_HOSTS these need the scheme. With DEBUG off and no entry here,
# admin login and every session-authenticated POST fail CSRF verification --
# the single most common "it worked locally" deployment failure for Django.
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
if RENDER_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_HOSTNAME}')

# Render terminates TLS at its edge and forwards plain HTTP inside the network,
# so this header is the only way Django can tell the original request was
# HTTPS. Without it request.is_secure() is always False, which makes the
# secure-cookie and redirect settings below either inert or an infinite loop.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# USE_X_FORWARDED_HOST is deliberately NOT enabled.
#
# The frontend proxies /api/* to this service, and that proxy forwards
# X-Forwarded-Host carrying the *frontend's* domain. Trusting it would make
# Django validate that name against ALLOWED_HOSTS instead of its own, and
# reject every proxied request with a DisallowedHost 400.
#
# It is also not a trustworthy header here: Render passes a client-supplied
# X-Forwarded-Host straight through rather than overwriting it, so any caller
# can set it to anything. The real Host header is what actually routed the
# request to this service, which makes it both correct and unspoofable.

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    # Render's own health check reaches the container over plain HTTP on the
    # internal port. Without this exemption the redirect above answers it with
    # a 301, Render reads that as unhealthy, and it kills a working deploy.
    SECURE_REDIRECT_EXEMPT = [r'^healthz/$']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
    },
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
DATABASES = {
    'default': (
        database_from_url(DATABASE_URL)
        if DATABASE_URL
        else {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django 5.1 removed STATICFILES_STORAGE/DEFAULT_FILE_STORAGE; STORAGES is the
# only supported form on 6.x. WhiteNoise was already in MIDDLEWARE but with no
# backend configured it was serving static files unhashed and uncompressed.
# The 'default' entry is where Supabase object storage will slot in later.
# Uploaded PDFs. A PaaS container's filesystem is ephemeral: anything written
# to MEDIA_ROOT is discarded on the next deploy or wake from sleep, and the
# failure is silent -- the database keeps rows pointing at files that no longer
# exist. So when a bucket is configured we store media there; with the
# variables unset, local disk stays the sensible default for development.
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')

if AWS_STORAGE_BUCKET_NAME:
    _media_storage = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'endpoint_url': os.getenv('AWS_S3_ENDPOINT_URL'),
            'region_name': os.getenv('AWS_S3_REGION_NAME'),
            'access_key': os.getenv('AWS_ACCESS_KEY_ID'),
            'secret_key': os.getenv('AWS_SECRET_ACCESS_KEY'),
            # Supabase's S3 gateway only speaks path-style addressing. The
            # virtual-host style boto3 prefers would resolve to a subdomain
            # that does not exist, and fails as a DNS error rather than
            # anything that points at the real cause.
            'addressing_style': 'path',
            # Serve uploads through expiring signed URLs instead of making the
            # bucket public -- these are the user's own documents, and a
            # guessable public URL is not an access control.
            'querystring_auth': True,
            # Two uploads of the same filename are two documents, not one
            # overwriting the other.
            'file_overwrite': False,
            'default_acl': None,
        },
    }
else:
    _media_storage = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

STORAGES = {
    'default': _media_storage,
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Logging
# ---------------------------------------------------------------------------
# Django's built-in console handler carries a require_debug_true filter, and
# its only other handler mails ADMINS. With DEBUG=False and no mail configured
# -- i.e. in production -- that means exception tracebacks are written
# absolutely nowhere: a 500 shows up in the platform log as silence.
#
# So the console handler here is deliberately unfiltered. On a PaaS, stdout is
# the log: the platform captures it, and anything not written there is lost.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        # 5xx with full traceback, and 4xx at WARNING.
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Where DisallowedHost lands. Django answers a bad Host with a bare 400
        # and no explanation, so without this the most common production
        # misconfiguration is also the least diagnosable one.
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
