# Generated by Django 6.0.7 on 2026-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
                ('original_filename', models.CharField(max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_ingested', models.BooleanField(default=True)),
            ],
        ),
    ]
