#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# Deployment values live in their own file rather than backend/.env, so that
# pointing production at Supabase never disturbs the local Docker setup. This
# file is gitignored, and is what you copy from when Render asks for secrets.
ENV_FILE="deploy.env"

BACKEND_ENV="backend/.env"
PY=$(command -v python || command -v python3 || echo python)

# Carry over anything already configured for local development, so the wizard
# offers it as a default instead of asking again for a key you already found.
seed_from_backend_env() {
  local key line
  for key in "$@"; do
    if ! grep -qE "^${key}=" "$ENV_FILE" 2>/dev/null; then
      line=$(grep -E "^${key}=" "$BACKEND_ENV" 2>/dev/null | tail -n1) || true
      [[ -n "${line:-}" ]] && printf '%s\n' "$line" >> "$ENV_FILE"
    fi
  done
  return 0
}
touch "$ENV_FILE"
seed_from_backend_env GROQ_API_KEY GROQ_MODEL GOOGLE_API_KEY

banner "Aixia deployment"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: database connection string"
say "Aixia keeps chat history AND its document search index in one Postgres,"
say "so this single URL covers both."
open_url "https://supabase.com/dashboard"
step "Open your 'aixia' project, then click Connect in the top bar."
step "Choose the 'Direct Connection string' tab."
step "Under 'Connection Method', select the SESSION POOLER radio button."
note "Supabase describes it as 'an alternative to direct connection when"
note "connecting via an IPv4 network' -- Render is exactly that network."
printf '
'
say "You need a URL that looks like this:"
note "    postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:5432/postgres"
printf '
'
say "Three things must be true:"
note "  - username is postgres.<project-ref>, with a dot"
note "  - host contains 'pooler'  (a db.<ref>.supabase.co host is IPv6-only,"
note "    and Render cannot reach it at all)"
note "  - port is 5432, not 6543"
printf '
'
note "Session and transaction mode are the same host on different ports, so if"
note "you only find the transaction pooler, just change 6543 to 5432. Session"
note "mode is required because the vector library uses psycopg3, whose prepared"
note "statements break under transaction pooling."
printf '
'
step "Replace [YOUR-PASSWORD] in the URL with the database password you saved."
warn "If the password contains @ # / ? or : you MUST percent-encode it:"
note "    @ -> %40    # -> %23    / -> %2F    ? -> %3F    : -> %3A"
note "An unencoded @ splits the URL at the wrong place and surfaces as a"
note "host-not-found error that points nowhere near the real cause."
ask_secret DATABASE_URL "Paste the session pooler URL:"
write_env DATABASE_URL "$DATABASE_URL"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: verify the database"
say "Checking that URL really works, before Render depends on it."
if "$PY" - "$DATABASE_URL" <<'PYCHECK'
import re
import sys

url = sys.argv[1]
host = re.sub(r'^.*@', '', url).split('/')[0]
if 'pooler.supabase.com' not in host:
    print(f"  ! host is {host}")
    print("  ! that is not the pooler; Render will probably fail to connect")
if host.endswith(':6543'):
    print("  ! port 6543 is the TRANSACTION pooler; session mode (5432) is required")
try:
    import psycopg
except ImportError:
    print("  - psycopg not installed here, skipping the live check")
    sys.exit(0)
try:
    with psycopg.connect(url, connect_timeout=15) as conn, conn.cursor() as cur:
        cur.execute('select version()')
        print('  connected:', cur.fetchone()[0].split(',')[0])
        cur.execute("select count(*) from pg_extension where extname='vector'")
        if cur.fetchone()[0]:
            print('  pgvector:  enabled')
        else:
            print('  ! pgvector is NOT enabled')
            print('  ! run this in the Supabase SQL editor:')
            print('  !   create extension if not exists vector;')
            sys.exit(1)
except Exception as exc:
    print(f'  ! connection failed: {type(exc).__name__}: {str(exc)[:200]}')
    sys.exit(1)
PYCHECK
then
  printf '  %s✓ database reachable, pgvector present%s\n' "$GREEN" "$RESET"
else
  warn "database check failed. Fix this now, or the deploy cannot work."
  confirm "Continue anyway?" || exit 1
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: object storage for uploaded PDFs"
say "Render wipes its disk on every deploy and every wake from sleep, so"
say "uploads need somewhere durable to live."
step "Storage -> your bucket -> the S3 Connection settings panel."
ask        AWS_STORAGE_BUCKET_NAME "Bucket name (e.g. aixia-media):"
ask        AWS_S3_ENDPOINT_URL     "S3 endpoint URL:"
ask        AWS_S3_REGION_NAME      "Region (e.g. us-west-1):"
ask        AWS_ACCESS_KEY_ID       "S3 access key ID:"
ask_secret AWS_SECRET_ACCESS_KEY   "S3 secret access key:"
write_env AWS_STORAGE_BUCKET_NAME "$AWS_STORAGE_BUCKET_NAME"
write_env AWS_S3_ENDPOINT_URL     "$AWS_S3_ENDPOINT_URL"
write_env AWS_S3_REGION_NAME      "$AWS_S3_REGION_NAME"
write_env AWS_ACCESS_KEY_ID       "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY   "$AWS_SECRET_ACCESS_KEY"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: verify object storage"
if "$PY" - "$AWS_S3_ENDPOINT_URL" "$AWS_S3_REGION_NAME" "$AWS_ACCESS_KEY_ID" \
          "$AWS_SECRET_ACCESS_KEY" "$AWS_STORAGE_BUCKET_NAME" <<'PYCHECK'
import sys

endpoint, region, key, secret, bucket = sys.argv[1:6]
try:
    import boto3
    from botocore.config import Config
except ImportError:
    print('  - boto3 not installed here, skipping the live check')
    sys.exit(0)
try:
    # Supabase only speaks path-style addressing; the virtual-host style boto3
    # prefers resolves to a subdomain that does not exist, and surfaces as a
    # DNS error rather than anything pointing at the real cause.
    s3 = boto3.client(
        's3', endpoint_url=endpoint, region_name=region,
        aws_access_key_id=key, aws_secret_access_key=secret,
        config=Config(s3={'addressing_style': 'path'}),
    )
    s3.put_object(Bucket=bucket, Key='.aixia-wizard-check', Body=b'ok')
    s3.delete_object(Bucket=bucket, Key='.aixia-wizard-check')
    print(f"  wrote then deleted a test object in '{bucket}'")
except Exception as exc:
    print(f'  ! storage check failed: {type(exc).__name__}: {str(exc)[:200]}')
    sys.exit(1)
PYCHECK
then
  printf '  %s✓ object storage reachable and writable%s\n' "$GREEN" "$RESET"
else
  warn "storage check failed. Uploads will not survive a restart until it passes."
  confirm "Continue anyway?" || exit 1
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "API keys"
say "Two providers, two jobs. Groq writes the answers; Gemini turns your"
say "documents into searchable vectors. Groq serves no embeddings endpoint,"
say "which is the only reason a second key exists."
note "Already in backend/.env? Press Enter to keep each one."
ask_secret GROQ_API_KEY   "Groq API key:"
ask        GROQ_MODEL     "Groq model:"
ask_secret GOOGLE_API_KEY "Google AI Studio key:"
write_env GROQ_API_KEY   "$GROQ_API_KEY"
write_env GROQ_MODEL     "$GROQ_MODEL"
write_env GOOGLE_API_KEY "$GOOGLE_API_KEY"

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub: push the repository"
say "Render and Vercel both deploy from GitHub, so the code has to be there."
if git rev-parse --git-dir >/dev/null 2>&1; then
  if git remote get-url origin >/dev/null 2>&1; then
    note "remote: $(git remote get-url origin)"
  else
    warn "no 'origin' remote yet."
    step "Create an empty repo at https://github.com/new - no README, no .gitignore."
    note "  then: git remote add origin https://github.com/<you>/<repo>.git"
    pause "Press Enter once the remote is added"
  fi
  if [[ -n "$(git status --porcelain)" ]]; then
    warn "uncommitted changes:"
    git status --short | head -20 | sed 's/^/      /'
    if confirm "Commit all of that and push?"; then
      git add -A
      git commit -q -m "feat: deploy backend to Render, frontend to Vercel, data to Supabase" || true
      if git push -u origin HEAD; then
        printf '  %s✓ pushed%s\n' "$GREEN" "$RESET"
      else
        SKIPPED+=("git push failed - push manually before deploying")
      fi
    else
      SKIPPED+=("commit and push before deploying, or Render builds stale code")
    fi
  else
    printf '  %s✓ working tree clean%s\n' "$GREEN" "$RESET"
    git push -u origin HEAD 2>/dev/null || true
  fi
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Render: create the backend service"
say "render.yaml already describes the service, so Render only needs secrets."
open_url "https://dashboard.render.com/blueprints"
step "New Blueprint Instance -> connect this repository -> Apply."
step "Render reads render.yaml and prompts for each secret."
printf '\n'
warn "Your values are in $ENV_FILE. Open that file and copy from it."
note "Render prompts for these ONLY at first creation. Anything skipped now has"
note "to be added by hand later, under the service's Environment tab."
printf '\n'
note "Leave CSRF_TRUSTED_ORIGINS and CORS_ALLOWED_ORIGINS empty for now: the"
note "Vercel URL does not exist yet. Stage 10 comes back and fills them in."
printf '\n'
step "Wait for the first deploy. The build takes a few minutes."
ask RENDER_BACKEND_URL "Paste the service URL (https://....onrender.com):"
write_env RENDER_BACKEND_URL "$RENDER_BACKEND_URL"

# ──────────────────────────────────────────────────────────────────────────
stage "Render: verify the backend"
say "Hitting the health endpoint. It deliberately does not touch the database,"
say "so a pass means the container booted and a fail is not a data problem."
code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 90 "${RENDER_BACKEND_URL%/}/healthz/" || echo 000)
if [[ "$code" == "200" ]]; then
  printf '  %s✓ backend is live (HTTP 200)%s\n' "$GREEN" "$RESET"
else
  warn "got HTTP $code from ${RENDER_BACKEND_URL%/}/healthz/"
  note "Check the Render logs. The usual causes are a bad DATABASE_URL - the"
  note "migrate step runs at boot and fails loudly - or the direct Supabase"
  note "connection string instead of the pooler."
  confirm "Continue anyway?" || exit 1
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Vercel: deploy the frontend"
open_url "https://vercel.com/new"
step "Import this GitHub repository."
warn "Set Root Directory to 'frontend', or the build will not find the app."
step "Add one environment variable:"
printf '\n'
note "    BACKEND_INTERNAL_URL = ${RENDER_BACKEND_URL%/}"
printf '\n'
note "Next.js proxies /api/* to that URL from the server side, so the browser"
note "only ever talks to Vercel. That is why normal use needs no CORS at all."
step "Deploy, and wait for the build to finish."
ask VERCEL_APP_URL "Paste the Vercel URL (https://....vercel.app):"
write_env VERCEL_APP_URL "$VERCEL_APP_URL"

# ──────────────────────────────────────────────────────────────────────────
stage "Render: allow the frontend origin"
say "Each service needed the other's URL, so Render takes a second pass."
open_url "https://dashboard.render.com"
step "Open aixia-backend -> Environment, and set both of these:"
printf '\n'
note "    CSRF_TRUSTED_ORIGINS = ${VERCEL_APP_URL%/}"
note "    CORS_ALLOWED_ORIGINS = ${VERCEL_APP_URL%/}"
printf '\n'
note "Both need the https:// scheme. Without CSRF_TRUSTED_ORIGINS, Django admin"
note "login fails CSRF verification now that DEBUG is off."
step "Save changes. Render redeploys on its own."
pause "Press Enter once that redeploy has finished"

# ──────────────────────────────────────────────────────────────────────────
stage "Smoke test"
open_url "${VERCEL_APP_URL%/}"
say "Final check, in order:"
step "The chat page loads."
step "Sign in at ${RENDER_BACKEND_URL%/}/admin/ and upload a PDF."
note "  No admin user yet? Open the Render service Shell and run:"
note "    python manage.py createsuperuser"
step "Ingest the document, then ask a question about it in the chat."
step "Confirm the answer streams in word by word, rather than landing at once."
printf '\n'
warn "The first request after ~15 minutes idle takes 20-30s: the free tier sleeps."
note "That is expected, not a bug."
printf '\n'
confirm "Did all of that work?" || SKIPPED+=("smoke test did not pass - check the Render logs")

finish
